name: Trigger Webhook

on:
  push:
    branches:
      - main

jobs:
  call_webhook:
    runs-on: ubuntu-latest
    steps:
      # 1. Webhook 호출
      - name: Call Webhook URL
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }} # Webhook URL을 GitHub Secrets로 설정
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"message": "GitHub Actions Triggered", "branch": "${{ github.ref_name }}"}' \
            $WEBHOOK_URL
