name: Health Check with Slack Notification

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  health_check:
    runs-on: ubuntu-latest

    steps:
      - name: Perform Health Check
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          URL="https://www.awscloudclubs.kr/"
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" $URL)
          if [ "$STATUS_CODE" -eq 200 ]; then
            echo "Health Check Passed. Status Code: $STATUS_CODE"
            curl -X POST -H 'Content-type: application/json' \
              --data '{"text":"Health Check Passed for AWS Cloud Clubs!"}' $WEBHOOK_URL
          else
            echo "Health Check Failed. Status Code: $STATUS_CODE"
            curl -X POST -H 'Content-type: application/json' \
              --data '{"text":"Health Check Failed for AWS Cloud Clubs! Status Code: '"$STATUS_CODE"'"}' $WEBHOOK_URL
            exit 1
          fi
